# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

env:
  - GITHUB_TOKEN
  - COSIGN_EXPERIMENTAL=true

before:
  hooks:
    - go mod download
    - go mod verify

builds:
  - binary: submit-hackernews
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - "-trimpath"
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X main.version={{.Version}}"
      - "-X main.commit={{.Commit}}"
      - "-X main.date={{.Date}}"
      - "-X main.builtBy=goreleaser"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - formats:
          - zip
        goos: windows
    name_template: "{{ .ProjectName }}_{{ tolower .Os }}_{{ .Arch }}"

dist: .goreleaser-dist

dockers_v2:
  - id: submit-hackernews
    images:
      - ghcr.io/meysam81/{{ .ProjectName }}
    dockerfile: Dockerfile.goreleaser
    platforms:
      - linux/amd64
    tags:
      - "{{ if not .IsSnapshot }}v{{ .Version }}{{ end }}"
      - "{{ if not .IsSnapshot }}v{{ .Major }}{{ end }}"
      - "{{ if not .IsSnapshot }}v{{ .Major }}.{{ .Minor }}{{ end }}"
      - "{{ if not .IsSnapshot }}v{{ .Major }}.{{ .Minor }}.{{ .Patch }}{{ end }}"
      - "{{ .FullCommit }}"
      - "{{ if not .IsSnapshot }}latest{{ end }}"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.description": "Submit links to Hacker News."
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.version": "{{.Version}}"

docker_signs:
  - id: default
    cmd: cosign
    args:
      - "sign"
      - "--yes"
      - "${artifact}"
    output: true

docker_digest:
  name_template: "digest.txt"
  disable: "{{ .Env.NO_DIGEST }}"

report_sizes: true

milestones:
  - close: true
    fail_on_error: false
    name_template: "{{ .Tag }}"

announce:
  skip: "{{gt .Patch 0}}"

checksum:
  algorithm: sha256
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
