apiVersion: batch/v1
kind: Job
metadata:
  name: submit-hackernews
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/meysam81/submit-hackernews
          name: submit-hackernews
          resources: {}
      restartPolicy: Never
