apiVersion: batch/v1
kind: CronJob
metadata:
  name: submit-hackernews
spec:
  schedule: "30 13 5 7 *" # July 5th at 1:30 PM every year
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          containers:
            - image: ghcr.io/meysam81/submit-hackernews
              name: submit-hackernews
              resources: {}
          restartPolicy: Never
